excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Subject.github.io
title: VICTOR MARTINS
tagline: WEB DEVELOPER
description: HTML 5,  CSS 3 E JAVASCRIPT<br />FOUNDATION ZURB
paginate: 10